"""
プロジェクトに対する設定を行う
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import secrets
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# 開発環境でのみ既定として許可するホストを定義する。
DEVELOPMENT_ALLOWED_HOSTS = ('localhost', '127.0.0.1', '[::1]')


# 文字列の環境変数を真偽値として厳密に読み取る。
def get_boolean_environment_variable(variable_name, default):
    raw_value = os.getenv(variable_name)
    if raw_value is None:
        return default

    normalized_value = raw_value.strip().lower()
    if normalized_value in {'1', 'true', 'yes', 'on'}:
        return True
    if normalized_value in {'0', 'false', 'no', 'off'}:
        return False
    raise ImproperlyConfigured(
        f'{variable_name} は true または false として設定してください。'
    )


# カンマ区切りの環境変数を空白なしの一覧として読み取る。
def get_list_environment_variable(variable_name, default):
    raw_value = os.getenv(variable_name)
    if raw_value is None:
        return list(default)

    values = [
        value.strip() for value in raw_value.split(',') if value.strip()
    ]
    if not values:
        raise ImproperlyConfigured(
            f'{variable_name} には少なくとも1つの値を設定してください。'
        )
    return values


# 本番用の設定値を環境変数から読み取り、必須値を検証する。
def load_environment_settings():
    debug = get_boolean_environment_variable('DJANGO_DEBUG', default=True)
    secret_key = os.getenv('DJANGO_SECRET_KEY')
    allowed_hosts = get_list_environment_variable(
        'DJANGO_ALLOWED_HOSTS',
        DEVELOPMENT_ALLOWED_HOSTS if debug else (),
    )

    if not secret_key or not secret_key.strip():
        if debug:
            # 開発時はソースコードに鍵を残さない一時鍵を使用する。
            secret_key = secrets.token_urlsafe(64)
        else:
            raise ImproperlyConfigured(
                'DJANGO_DEBUG=false のときは DJANGO_SECRET_KEY が必要です。'
            )
    if not debug and not allowed_hosts:
        raise ImproperlyConfigured(
            'DJANGO_DEBUG=false のときは DJANGO_ALLOWED_HOSTS が必要です。'
        )
    return debug, secret_key, allowed_hosts


# 環境変数を評価して、Djangoが使用する本番・開発共通の設定値を決定する。
DEBUG, SECRET_KEY, ALLOWED_HOSTS = load_environment_settings()


# Application definition

INSTALLED_APPS = [
    'basemodel.apps.BasemodelConfig',
    'list.apps.ListConfig',
    'search.apps.SearchConfig',
    'home.apps.HomeConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'utility': 'list.templatetags.mypaginator' # urlのGETを引き継ぐ
            }
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'etenki': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'etenki.db',
    },
}
DATABASE_ROUTERS = ['mysite.db_router.DBRouter']

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'static'
PDF_URL='https://www.metsoc.jp/tenki/pdf/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
