# 空の検索用DBに、記事・カテゴリ・著者を管理する最終スキーマを作成する。
# Generated by Django 5.2.17 on 2026-10-01

import django.db.models.deletion
from django.db import migrations, models


# 空DB専用の初期スキーマを定義する。
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name': '著者',
                'verbose_name_plural': '著者',
            },
        ),
        migrations.CreateModel(
            name='Bunrui',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '内容分類',
                'verbose_name_plural': '内容分類',
            },
        ),
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_order', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name': '原稿種別',
                'verbose_name_plural': '原稿種別',
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name': 'キーワード',
                'verbose_name_plural': 'キーワード',
            },
        ),
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='article_author_links',
                        to='list.author',
                    ),
                ),
            ],
            options={
                'verbose_name': '記事の著者',
                'verbose_name_plural': '記事の著者',
                'db_table': 'list_kijis_author',
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, unique=True)),
                (
                    'group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='categories',
                        to='list.categorygroup',
                    ),
                ),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='Kijis',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('volume', models.TextField(blank=True, null=True)),
                (
                    'startpage',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ('no', models.TextField(blank=True, null=True)),
                ('pdf', models.CharField(blank=True, max_length=50, null=True)),
                (
                    'author',
                    models.ManyToManyField(
                        blank=True,
                        related_name='author',
                        through='list.ArticleAuthor',
                        through_fields=('kijis', 'author'),
                        to='list.author',
                    ),
                ),
                (
                    'bunrui',
                    models.ManyToManyField(
                        blank=True,
                        related_name='bunrui',
                        to='list.bunrui',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='category',
                        to='list.category',
                    ),
                ),
                (
                    'keyword',
                    models.ManyToManyField(
                        blank=True,
                        related_name='keyword',
                        to='list.keyword',
                    ),
                ),
            ],
            options={
                'verbose_name': '記事',
                'verbose_name_plural': '記事',
            },
        ),
        migrations.AddField(
            model_name='articleauthor',
            name='kijis',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='author_links',
                to='list.kijis',
            ),
        ),
    ]
