# Generated by Django 2.2.6 on 2019-12-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kijis',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='author', to='list.Author'),
        ),
        migrations.AlterField(
            model_name='kijis',
            name='bunrui',
            field=models.ManyToManyField(blank=True, related_name='bunrui', to='list.Bunrui'),
        ),
        migrations.AlterField(
            model_name='kijis',
            name='keyword',
            field=models.ManyToManyField(blank=True, related_name='keyword', to='list.Keyword'),
        ),
    ]
