# Generated by Django 5.2.17 on 2026-09-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_alter_author_id_alter_bunrui_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '著者', 'verbose_name_plural': '著者'},
        ),
        migrations.AlterModelOptions(
            name='bunrui',
            options={'verbose_name': '内容分類', 'verbose_name_plural': '内容分類'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'カテゴリ', 'verbose_name_plural': 'カテゴリ'},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'verbose_name': 'キーワード', 'verbose_name_plural': 'キーワード'},
        ),
        migrations.AlterModelOptions(
            name='kijis',
            options={'verbose_name': '記事', 'verbose_name_plural': '記事'},
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
