# 空の検索用DBに、巻・号を管理する最終スキーマを作成する。
# Generated by Django 5.2.17 on 2026-10-01

import django.db.models.deletion
from django.db import migrations, models


# 空DB専用の初期スキーマを定義する。
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('year', models.PositiveSmallIntegerField()),
                ('volume', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': '巻',
                'verbose_name_plural': '巻',
                'constraints': [
                    models.UniqueConstraint(
                        fields=('volume',),
                        name='search_year_unique_volume',
                        violation_error_message='同じ巻番号が既に登録されています。',
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('no', models.PositiveSmallIntegerField()),
                ('start_page', models.PositiveSmallIntegerField()),
                (
                    'volume',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='search.year',
                    ),
                ),
            ],
            options={
                'verbose_name': '号',
                'verbose_name_plural': '号',
                'constraints': [
                    models.UniqueConstraint(
                        fields=('volume', 'no'),
                        name='search_month_unique_volume_no',
                        violation_error_message='同じ巻に同じ号は登録できません。',
                    ),
                ],
            },
        ),
    ]
