# Generated by Django 2.2.6 on 2019-11-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='month',
            table=None,
        ),
        migrations.AlterModelTable(
            name='year',
            table=None,
        ),
    ]
