# Generated by Django 2.2.6 on 2019-12-09 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20191126_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.Year'),
        ),
    ]
