# Generated by Django 2.2.6 on 2019-12-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kiji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bunrui', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('title_jp', models.CharField(blank=True, max_length=400, null=True)),
                ('author_jp', models.CharField(blank=True, max_length=256, null=True)),
                ('volume', models.TextField(blank=True, null=True)),
                ('start_page', models.SmallIntegerField(blank=True, null=True)),
                ('no', models.TextField(blank=True, null=True)),
                ('keyword', models.CharField(blank=True, max_length=256, null=True)),
                ('pdf', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'kiji',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Naiyou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'naiyou',
                'managed': False,
            },
        ),
    ]
